<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetAccountValuesRequest</code>
 */
class GetAccountValuesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Массив счетов пользователя.
     *
     * Generated from protobuf field <code>repeated string accounts = 1;</code>
     */
    private $accounts;
    /**
     * Массив запрашиваемых параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValue values = 2;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $accounts
     *           Массив счетов пользователя.
     *     @type int[] $values
     *           Массив запрашиваемых параметров.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Массив счетов пользователя.
     *
     * Generated from protobuf field <code>repeated string accounts = 1;</code>
     * @return RepeatedField<string>
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Массив счетов пользователя.
     *
     * Generated from protobuf field <code>repeated string accounts = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->accounts = $arr;

        return $this;
    }

    /**
     * Массив запрашиваемых параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValue values = 2;</code>
     * @return RepeatedField<int>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Массив запрашиваемых параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValue values = 2;</code>
     * @param int[] $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Tinkoff\Invest\V1\AccountValue::class);
        $this->values = $arr;

        return $this;
    }

}

