<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetAccountValuesResponse</code>
 */
class GetAccountValuesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Массив счетов с параметрами.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValuesWithParameters accounts = 1;</code>
     */
    private $accounts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\AccountValuesWithParameters[] $accounts
     *           Массив счетов с параметрами.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Массив счетов с параметрами.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValuesWithParameters accounts = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\AccountValuesWithParameters>
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Массив счетов с параметрами.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.AccountValuesWithParameters accounts = 1;</code>
     * @param \Tinkoff\Invest\V1\AccountValuesWithParameters[] $var
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\AccountValuesWithParameters::class);
        $this->accounts = $arr;

        return $this;
    }

}

